name: Build

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: "Version & tag name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        if: ${{ github.event.inputs.version }}
        with:
          tag: ${{ github.event.inputs.version }}

      - name: Release version
        uses: ncipollo/release-action@v1
        if: ${{ github.event.inputs.version }}
        with:
          artifacts: "build/libs/*.jar"
          tag: ${{ github.event.inputs.version }}
